version: '3'
services:
    nginx_web_1:
        container_name: web1
        build:
            context: ./nginx/web1
        image:
            niegowic/web1
        expose:
            - 80
        networks:
            public_net:
                ipv4_address: 172.16.0.100
                aliases: 
                    - nginx1
    nginx_web_2:
        container_name: web2
        build:
            context: ./nginx/web2
        image:
            niegowic/web2
        expose:
            - 80
        networks:
            public_net:
                ipv4_address: 172.16.0.101
                aliases: 
                    - nginx2
    haproxy:
        build:
            context: ./haproxy
        image:
            niegowic/haproxy
        ports:
            - 80:80
        expose:
            - 80
        networks:
            public_net:
                ipv4_address: 172.16.0.2
        environment:
            - NGINX_1_IP=172.16.0.100
            - NGINX_2_IP=172.16.0.101
            - NGINX_EXPOSED_PORT=80
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.0.0/24